#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$ROOT_DIR/.codex/environments/environment.toml"

/bin/mkdir -p "$(dirname "$TARGET")"

/bin/cat > "$TARGET" <<'TOML'
# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY
# Regenerate with: ./script/generate_codex_environment.sh
version = 1
name = "MusicFloat"

[setup]
script = ""

[[actions]]
name = "Run"
icon = "run"
command = "./script/build_and_run.sh"

[[actions]]
name = "Verify App"
icon = "check"
command = "./script/build_and_run.sh --verify"

[[actions]]
name = "Test"
icon = "test"
command = "xcodebuild test -project MusicFloat.xcodeproj -scheme MusicFloat -destination 'platform=macOS' -derivedDataPath .codex/DerivedData"

[[actions]]
name = "Xcode MCP Mac Tools"
icon = "list"
command = "xcodebuildmcp tools --workflow macos"

[[actions]]
name = "Xcode MCP IDE Tools"
icon = "list"
command = "xcodebuildmcp xcode-ide list-tools"

[[actions]]
name = "Xcode MCP Build"
icon = "build"
command = "xcodebuildmcp macos build"

[[actions]]
name = "Xcode MCP Test"
icon = "test"
command = "xcodebuildmcp macos test"

[[actions]]
name = "Agent Verify"
icon = "check"
command = "./script/agent_verify.sh"

[[actions]]
name = "Doctor"
icon = "info"
command = "./script/profile.sh doctor"

[[actions]]
name = "Profile Report"
icon = "list"
command = "./script/profile.sh report"

[[actions]]
name = "Profile Disk"
icon = "storage"
command = "./script/profile.sh disk"

[[actions]]
name = "Release Status"
icon = "info"
command = "script/release_self.sh --status"
TOML

printf "Generated %s\n" "$TARGET"
